# Generated by Django 6.1.1 on 2026-09-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('recyclable', models.BooleanField()),
                ('preparation', models.TextField()),
            ],
        ),
    ]
