# Generated by Django 6.1.1 on 2026-09-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteitem',
            name='preparation',
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='hazard_class',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='map_filter_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='preparation_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='what_happens_next',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
