# Generated by Django 6.1.1 on 2026-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_remove_wasteitem_preparation_wasteitem_hazard_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropoffPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('working_hours', models.CharField(max_length=300)),
                ('description', models.TextField(default='')),
                ('accepted_types', models.ManyToManyField(blank=True, related_name='dropoff_points', to='waste.wasteitem')),
            ],
        ),
    ]
